- hosts: mmm-pre1 mmm-pre2 mmm-pre3
  user: root
  vars:
    user_home: duowei
    # user_passwd: 
    solr_cloud_001: *.*.*.*
    solr_cloud_002: *.*.*.*
    solr_cloud_003: *.*.*.*
  roles:
    - pre-solr-zookeeper
  tasks:
