- hosts: mmm-pre1 mmm-pre2 mmm-pre3
  user: root
  vars:
    user_home: duowei
    # user_passwd: 
    zk_cluster_list:
      - {name: 'server.1', ip: '*.*.*.*'}
      - {name: 'server.2', ip: '*.*.*.*'}
      - {name: 'server.3', ip: '*.*.*.*'}
  roles:
    - zookeeper-cluster
  tasks:
