apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ servername }}server-deployment
  namespace: vvic-pre-release
spec:
  replicas: {{ replicas }}
#滚动更新策略:最大激增数：25%, 最大无效数：25%
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  "revisionHistoryLimit": 10
  "progressDeadlineSeconds": 600
  template:
    metadata:
      labels:
        app: {{ servername }}server
    spec:
      containers:
        - name: {{ servername }}server
          image: "{{ image }}"
          ports:
            - name: {{ servername }}server
              containerPort: {{ containerPort }}
              hostPort: {{ hostPort }}
          envFrom:
            - configMapRef:
                name: {{ servername }}-env
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 0.06
              memory: 1Gi