apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-{{ servername }}
  namespace: vvic-pre-release
  labels:
    app: hpa
    version: v0.0.1
spec:
  scaleTargetRef:
    apiVersion: v1
    kind: Deployment
    name: {{ servername }}server-deployment
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 90

