---
# possibly saved as sysinit/roles/nginx-1.12.1/tasks/main.yml
- name: check_user {{user_home}}
  shell: id -u {{user_home}}
  register: user_result
  ignore_errors: True

- name: check /home/{{user_home}}
  shell: ls /home/{{user_home}}
  register: dir_result
  ignore_errors: True

- name: 新建用户{{user_home}}
  shell: adduser {{user_home}}
  when: user_result is failed

- name: 新建用户目录
  file: dest=/home/{{user_home}} state=directory owner={{user_home}} group={{user_home}}
  when: dir_result is failed

- name: mkdir /home/{{user_home}}/apps
  file: dest=/home/{{user_home}}/apps state=directory mode=0754  owner={{user_home}} group={{user_home}}

- name: mkdir /home/{{user_home}}/tools
  file: dest=/home/{{user_home}}/tools state=directory mode=0754  owner={{user_home}} group={{user_home}}
  
- name: 拷贝所有安装包
  copy: src=nginx/ dest=/home/{{user_home}}/tools/ owner={{user_home}} group={{user_home}} mode=700

- name: 解压安装包nginx-1.12.1.tar.gz
  shell: cd /home/{{user_home}}/tools && tar -xvf nginx-1.12.1.tar.gz

- name: 解压安装包ngx_devel_kit-0.3.0.tar.gz
  shell: cd /home/{{user_home}}/tools && tar -xvf ngx_devel_kit-0.3.0.tar.gz
  
- name: 解压安装包openssl-1.0.1t.tar.gz
  shell: cd /home/{{user_home}}/tools && tar -xvf openssl-1.0.1t.tar.gz

- name: 解压安装包pcre-8.38.tar.gz
  shell: cd /home/{{user_home}}/tools && tar -xvf pcre-8.38.tar.gz
  
- name: 解压安装包zlib-1.2.8.tar.gz
  shell: cd /home/{{user_home}}/tools && tar -xvf zlib-1.2.8.tar.gz

- name: 编译nginx模块openssl-1.0.1t
  shell: cd /home/{{user_home}}/tools/openssl-1.0.1t && ./config && make && make install
  
- name: 编译nginx模块zlib-1.2.8
  shell: cd /home/{{user_home}}/tools/zlib-1.2.8 && ./configure && make && make install
  
- name: 编译nginx模块zlib-1.2.8
  shell: cd /home/{{user_home}}/tools/pcre-8.38 && ./configure && make && make install

- name: 拷贝安装模板nginx-1.12.1.sh
  template: src=nginx-1.12.1.tem dest=/home/{{user_home}}/tools/install-nginx-1.12.1.sh owner=root group=root mode=0700

- name: 编译安装nginx-1.12.1
  shell: /home/{{user_home}}/tools/install-nginx-1.12.1.sh