---
# possibly saved as ansible/sysinit/roles/sysctl/defaults/main.yml
# ara_apt_packages: 
  # - gcc 
  # - python-dev
  # - libffi-dev
  # - libssl-dev
  # - python-pip
  # - libxml2-dev
  # - libxslt1-dev

# ara_pip_packages:
  # - tox
  # - ara 
user_root: root
user_run: vvic_run
user_user: vvic_user

version_path: /data/Version
init_path: /data
tool_path: /data/softwares
run_path: /data/monitor-agent
ini_path: /data/softwares/supervisor/supervisord.d
ini_url: http://192.168.201.148:8557/open-falcon/monitor-agent.ini
agent_url: http://192.168.201.148:8557/open-falcon/monitor-agent.tar.gz
agent_gz: monitor-agent.tar.gz

