---
# possibly saved as sysinit/roles/ssh/tasks/main.yml
- name: 新建/root/.ssh目录
  file: dest=~/.ssh state=directory mode=0700  owner=root group=root
- name: 拷贝root公钥
  copy: src=./root/authorized_keys dest=~/.ssh/ mode=0644 owner=root group=root
- name: 新建{{user_home}}用户
  shell: useradd {{user_home}}
- name: 新建/{{user_home}}/.ssh目录
  file: dest=/home/{{user_home}}/.ssh state=directory mode=0700  owner={{user_home}} group={{user_home}}
- name: 拷贝{{user_home}}公钥
  copy: src=./{{user_home}}/authorized_keys dest=~/.ssh/ mode=0644 owner={{user_home}} group={{user_home}}
- name: 允许mmm-pre0 root登录，允许{{user_home}}用户登录，修改ssh端口
  shell: sed -i 's/Port 22/Port 18791/g' /etc/ssh/sshd_config
  shell: sed -i 's/PermitRootLogin yes/#PermitRootLogin yes/g' /etc/ssh/sshd_config
  shell: echo 'Allowusers root@mmm-pre0' >> /etc/ssh/sshd_config
  shell: echo 'Allowusers {{user_home}}@*.*.*.*' >> /etc/ssh/sshd_config
  service: name=ssh state=restarted



	  
