---
# possibly saved as sysinit/roles/ssh/tasks/main.yml
- name: 新建/root/.ssh目录
  file: dest=/home/root/.ssh state=directory mode=0700  owner=root group=root

- name: 拷贝root公钥
  copy: src=root/authorized_keys dest=/root/.ssh/ mode=0644 owner=root group=root

- name: 新建/{{user_home}}/.ssh目录
  file: dest=/home/{{user_home}}/.ssh state=directory mode=0700  owner={{user_home}} group={{user_home}}

- name: 拷贝{{user_home}}公钥
  copy: src={{user_home}}/authorized_keys dest=/home/{{user_home}}/.ssh/ mode=0644 owner={{user_home}} group={{user_home}}

# - name: /etc/hosts 添加mmm-pre0
  # shell: echo '{{ansible_ip}} {{ansible_hostname}}' >> /etc/hosts
  
- name: 修改ssh端口
  shell: sed -i 's/Port 22/Port 18791/g' /etc/ssh/sshd_config && sed -i 's/#Port 18791/Port 18791/g' /etc/ssh/sshd_config

- name: 限制root用户远程登录
  shell: sed -i 's/PermitRootLogin yes/#PermitRootLogin yes/g' /etc/ssh/sshd_config

- name: 允许mmm-pre0 root登录
  shell: echo 'Allowusers root@{{ansible_ip}}' >> /etc/ssh/sshd_config

- name: 允许{{user_home}}用户登录
  shell: echo 'Allowusers {{user_home}}@*.*.*.*' >> /etc/ssh/sshd_config

- name: 重启ssh服务
  service: name=sshd state=restarted
