---
# possibly saved as sysinit/roles/nfs-client/tasks/main.yml
- name: Ubuntu安装lrzsz
  apt: name=lrzsz state=present update_cache=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: CentOS安装lrzsz
  yum: name=lrzsz state=present update_cache=yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

