---
# possibly saved as sysinit/roles/docker/tasks/main.yml
- name: check docker
  shell: docker --version
  register: docker_result
  ignore_errors: True

- name: 更新docker网站的ssl key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  when: ansible_distribution == 'Ubuntu' and docker_result is failed

- name: 安装software-properties-common
  apt: name=software-properties-common state=present update_cache=yes
  when: ansible_distribution == 'Ubuntu' and docker_result is failed

- name: 添加docker安装源
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  when: ansible_distribution == 'Ubuntu' and docker_result is failed

- name: 更新安装源信息
  apt: update_cache=yes
  when: ansible_distribution == 'Ubuntu' and docker_result is failed

- name: 安装docker-ce={{docker_version}}
  apt: name=docker-ce={{docker_version}} state=present
  when: ansible_distribution == 'Ubuntu' and docker_result is failed
  
- name: 添加新用户{{user_home}}，允许执行docker命令
  shell: usermod -aG docker {{user_home}}
  
- name: 拷贝docker-compose
  copy: src=docker-compose dest=/usr/local/bin/ mode=0755 owner=root group=root