- hosts: mmm-pre1 mmm-pre2 mmm-pre3
  user: root
  vars:
    user_home: duowei
    # user_passwd: 
    solr_cloud_001: *.*.*.*
    solr_cloud_002: *.*.*.*
    solr_cloud_003: *.*.*.*
  roles:
    - solr-zookeeper
  tasks:
    - name: 启动solr cloud
      shell: /home/{{user_home}}/apps/solr-5.4.0/bin/solr restart -cloud -s /home/{{user_home}}/datas/solr_home -z {{solr_cloud_001}}:2181,{{solr_cloud_002}}:2181,{{solr_cloud_003}}:2181