---
# possibly saved as sysinit/roles/user/tasks/main.yml
- name: check_user {{user_home}}
  shell: id -u {{user_home}}
  register: user_result
  ignore_errors: True

- name: check /home/{{user_home}}
  shell: ls /home/{{user_home}}
  register: dir_result
  ignore_errors: True

# - name: 新建用户{{user_home}}
  # user: name={{user_home}} password={{user_passwd}} shell=/bin/bash uid=1000 home=/home/{{user_home}}
  # when: user_result is failed
  
- name: 新建用户{{user_home}}
  user: name={{user_home}} shell=/bin/bash uid=1000 home=/home/{{user_home}}
  when: user_result is failed

- name: 新建用户目录
  file: dest=/home/{{user_home}} state=directory owner={{user_home}} group={{user_home}}
  when: dir_result is failed

- name: mkdir /home/{{user_home}}/apps
  file: dest=/home/{{user_home}}/apps state=directory mode=0754  owner={{user_home}} group={{user_home}}

- name: mkdir /home/{{user_home}}/datas
  file: dest=/home/{{user_home}}/datas state=directory mode=0754  owner={{user_home}} group={{user_home}}

- name: mkdir /home/{{user_home}}/temps
  file: dest=/home/{{user_home}}/temps state=directory mode=0754  owner={{user_home}} group={{user_home}}

- name: mkdir /home/{{user_home}}/tools
  file: dest=/home/{{user_home}}/tools state=directory mode=0754  owner={{user_home}} group={{user_home}}

- name: mkdir /home/{{user_home}}/tasks
  file: dest=/home/{{user_home}}/tasks state=directory mode=0754  owner={{user_home}} group={{user_home}}

- name: mkdir /home/{{user_home}}/dockers
  file: dest=/home/{{user_home}}/dockers state=directory mode=0754  owner={{user_home}} group={{user_home}}

- name: mkdir /home/{{user_home}}/logs
  file: dest=/home/{{user_home}}/logs state=directory mode=0754  owner={{user_home}} group={{user_home}}
