---
# possibly saved as sysinit/roles/gdebi-core/tasks/main.yml
- name: Ubuntu安装aptitude
  apt: name=gdebi-core state=present update_cache=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'