---
# possibly saved as sysinit/roles/jdk8/tasks/main.yml
- name: check /home/{{user_home}}
  shell: ls /home/{{user_home}}
  register: result0
  ignore_errors: True

- name: check /home/{{user_home}}/tools
  shell: ls /home/{{user_home}}/tools
  register: result1
  ignore_errors: True

- name: check /home/{{user_home}}/apps
  shell: ls /home/{{user_home}}/apps
  register: result2
  ignore_errors: True
  
- name: check jdk8
  shell: java -version
  register: jdk8_result
  ignore_errors: True

- name: check JAVA_HOME
  shell: cat /etc/profile | grep JAVA_HOME
  register: JAVA_HOME_result
  ignore_errors: True

- name: 新建目录/home/{{user_home}}
  file: dest=/home/{{user_home}}/tools state=directory owner={{user_home}} group={{user_home}}
  when: result0 is failed

- name: 新建目录/home/{{user_home}}/tools
  file: dest=/home/{{user_home}}/tools state=directory owner={{user_home}} group={{user_home}}
  when: result1 is failed

- name: 新建目录/home/{{user_home}}/apps
  file: dest=/home/{{user_home}}/apps state=directory owner={{user_home}} group={{user_home}}
  when: result2 is failed

- name: 拷贝jdk8安装包
  copy: src=jdk-8u101-linux-x64.tar.gz dest=/home/{{user_home}}/tools/ mode=750 owner={{user_home}} group={{user_home}}
  when: jdk8_result is failed

- name: 解压压缩包到指定目录/home/{{user_home}}/apps
  shell: cd /home/{{user_home}}/tools && tar zxvf jdk-8u101-linux-x64.tar.gz -C /home/{{user_home}}/apps
  when: jdk8_result is failed

- name: 修改所有者
  file: dest=/home/{{user_home}}/apps/jdk1.8.0_101 state=directory owner={{user_home}} group={{user_home}} recurse=yes
  when: jdk8_result is failed

- name: 添加环境变量JAVA_HOME
  shell: echo 'export JAVA_HOME=/home/{{user_home}}/apps/jdk1.8.0_101' >> /etc/profile && echo 'export PATH=${JAVA_HOME}/bin:$PATH' >> /etc/profile
  when: JAVA_HOME_result is failed

- name: 环境变量立即生效
  sudo: no
  shell: source /etc/profile
  args:
    executable: /bin/bash
  when: JAVA_HOME_result is failed


